services:
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    ports:
      -"3000:3000"
      -"3000:3001"
      -"3000:3002"
      - "5232:5232"
    volumes:
      - ./data:/data
      - ./config:/config:ro
    # environment:
      # optionally: override UID/GID if host permissions matter
      # - UID=1000
      # - GID=1000
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5232/"]
      interval: 30s
      retries: 3
