services:
  app:
    build: app
    container_name: prosweet-caldav
    networks: [appnet]
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CALDAV_URL=http://radicale:5232

  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    networks: [appnet]
    ports:
      - "5232:5232"
    volumes:
      - ./radicale/data:/data
      - ./radicale/config:/config:ro
    # environment:
      # optionally: override UID/GID if host permissions matter
      # - UID=1000
      # - GID=1000
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5232/"]
      interval: 30s
      retries: 3

networks:
  appnet:
    driver: bridge

